version: 2
updates:

  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "JonaC22"
    assignees:
      - "JonaC22"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "JonaC22"
    assignees:
      - "JonaC22"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "JonaC22"
    assignees:
      - "JonaC22"
