[package]
name = "portfolio-cli"
version = "1.0.0"
authors = ["jonac22 <jonathan.corallo.utn@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
web3 = "0.13.0"
config = "0.10.1"
tokio = { version = "0.3.2", features = ["macros"] }
reqwest = "0.10.8"
jql = "2.7.4"
serde_json = "1.0.59"
