[package]
name = "portfolio-cli"
version = "0.1.0"
authors = ["Jonathan <JonaC22@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
web3 = "0.15.0"
config = "0.10.1"
tokio = { version = "0.2.22", features = ["macros"] }
reqwest = "0.10.8"
jql = "2.9.0"
serde_json = "1.0.59"
governor = "0.3.1"
nonzero_ext = "0.2.0"
indicatif = "0.16.1"
piechart = "0.1.2"
rand = "0.8.0"
clap = "2.33.3"
prettytable-rs = "0.8"
sled = "0.34.6"
